// <auto-generated />
using System;
using DepartmentAndEmployeeCoreApp.DbContext1;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DepartmentAndEmployeeCoreApp.Migrations
{
    [DbContext(typeof(ContactDbContext))]
    [Migration("20210417120431_deptAndEMpv1")]
    partial class deptAndEMpv1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DepartmentAndEmployeeCoreApp.Model.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Department");
                });

            modelBuilder.Entity("DepartmentAndEmployeeCoreApp.Model.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("age")
                        .HasColumnType("int");

                    b.Property<Guid?>("depatartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("depatartmentId");

                    b.ToTable("Employee");
                });

            modelBuilder.Entity("DepartmentAndEmployeeCoreApp.Model.Employee", b =>
                {
                    b.HasOne("DepartmentAndEmployeeCoreApp.Model.Department", "depatartment")
                        .WithMany("Employees")
                        .HasForeignKey("depatartmentId");

                    b.Navigation("depatartment");
                });

            modelBuilder.Entity("DepartmentAndEmployeeCoreApp.Model.Department", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
